server:
  port: 8081
  servlet:
      context-path: /api
      jsp:
        registered: false
  error:
    whitelabel: 
      enabled: false
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsec?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CET
    username: root
    password: 
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
       ddl-auto: create
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
